version: '2'
services:
  #########################
  # CSIO Twilio video SHIM demo application
  #########################

  twilio-video-shim-demo:
    build:
      context: ./../callstats-jssip-demo
    environment:
      ASTERISK_SERVER : ''
      SIP_USER_PASSWORD : ''
      CSIO_APP_ID : ''
      CSIO_APP_SECRET : ''
      PORT: '9090'
    ports:
      - "9090:9090"
    command: "npm start"
