version: '2'
services:
  #########################
  # CSIO JsSIP SHIM with demo application
  #########################

  jssip-shim-demo:
    build:
      context: ./../callstats-jssip-demo
    environment:
      ASTERISK_SERVER : ''
      CSIO_APP_ID : ''
      CSIO_APP_SECRET : ''
      PORT : '9090'
    ports:
      - "9090:9090"
    command: "npm start"
